#!/bin/bash

TEMP_RAW=$(sensors | grep 'Package id' | awk '{print $4}' | sed 's/[^0-9.]//g')

if (( $(echo "$TEMP_RAW < 60" | bc -l) )); then
    COLOR="#00FF00"
elif (( $(echo "$TEMP_RAW < 80" | bc -l) )); then
    COLOR="#FFFF00"
else
    COLOR="#FF0000"
fi

if [[ "$BLOCK_BUTTON" == "1" ]]; then
    SNAP=$(ps -eo %cpu,comm --sort=-%cpu | grep -vE '^\s*%CPU|ps'| head -n 6 | tail -n +2 | awk '{printf "%s%%  %s\n", $1, $2}')
    notify-send -t 3000 "CPU" "$SNAP"
fi
echo "<span foreground=\"${COLOR}\">CPU: ${TEMP_RAW}°C</span>"

