#!/bin/bash

MEDIA_WORKSPACE="4"
PRIMARY="DP-4"
SECONDARY="DP-0"


get_ws_monitor() {
    local workspace="$1"
    i3-msg -t get_workspaces | jq -r --arg ws "$workspace" '.[] | select(.name==$ws) | .output'
}


get_focused_workspace() {
    i3-msg -t get_workspaces | jq -r '.[] | select(.focused).name'
}

is_media_visible() {
    i3-msg -t get_workspaces | jq  '.[] | select(.visible) | .name' | grep -q "$MEDIA_WORKSPACE"
}

toggle_workspace() {
    local target
    local current=$(get_ws_monitor $MEDIA_WORKSPACE)
    local current_ws=$(get_focused_workspace)
    local focused_mon=$(get_ws_monitor $current_ws)
    eval $(xdotool getmouselocation --shell)
    if [[ "$current" != "$PRIMARY" ]] || !(is_media_visible); then
        target="$PRIMARY"
    else
        target="$SECONDARY"
    fi
    i3-msg "workspace $MEDIA_WORKSPACE; move workspace to output $target;"  > /dev/null
    if [[ "$target" == "$SECONDARY" || "$focused_mon" != "$PRIMARY" ]]; then
        i3-msg "workspace $current_ws"  > /dev/null
        xdotool mousemove $X $Y
    fi
}

TEXT=""
SHORT_TEXT=""
COLOR=""


if [[ "$BLOCK_BUTTON" == "1" ]]; then
    toggle_workspace
    pkill -RTMIN+2 i3blocks
fi

CURRENT=$(get_ws_monitor $MEDIA_WORKSPACE)
if [[ "$CURRENT" == "$PRIMARY" ]] && is_media_visible; then
    TEXT="📺"
    COLOR="#FF6F61"
else
    TEXT="🛠️"
    COLOR="#4682B4"
fi

echo "$TEXT"
echo "$SHORT_TEXT"
echo "$COLOR"
