#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    choices=$(find  ~/school ~/personal/godot ~/handel ~/personal -mindepth 1 -maxdepth 1 -type d)
    choices+=" "$(readlink -f ~/.config/nvim)
    selected=$(echo $choices| tr ' ' '\n' | fzf --tmux)
fi

if [[ -z $selected ]]; then
    exit 0
fi
selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

venv="${selected}/.venv/bin/activate"

if [[ -f $venv ]]; then
    tmux send-keys -t $selected_name "source $venv" ENTER "clear" ENTER
fi

tmux switch-client -t $selected_name
